Automatiz\UserBundle\Entity\User:
    exclusion_policy: ALL
    properties :
      id :
        expose : true
        groups: [cocktail_info, cocktail_detail, user_info, user_detail]
      firstname:
        expose : true
        groups: [user_detail]
      lastname:
        expose : true
        groups: [user_detail]