Automatiz\UserBundle\Entity\User:
    exclusion_policy: ALL
    properties :
      id :
        expose : true
        groups: [cocktail_info, cocktail_detail, details_user, me, list]
      firstname:
        expose : true
        groups: [details_user, me]
      lastname:
        expose : true
        groups: [details_user, me]