# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        #api_host:
        #    host: automatiz\.local
        #    pattern:    /api/.*
        #    http_basic: true
        #    stateless:  true
        # disables authentication for assets and the profiler, adapt it according to your needs
        api_oauth:
            pattern: ^/api                             # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true                           # Anonymous access is not allowed
            host: api\.automatiz\.local

        main:
            host: automatiz\.local
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                remember_me: true
                default_target_path: /
            logout:       true
            anonymous:    true

        oauth_token:                                   # Everyone can access the access token URL.
            host: api\.automatiz\.local
            pattern: ^/oauth/v2/token
            security: false

        oauth_authorize:
            host: api\.automatiz\.local
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
            anonymous: true

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/images, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { host: automatiz\.local, path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { host: api\.automatiz\.local, path: ^/api/cocktails, role: ROLE_COCKTAILS }
        - { host: api\.automatiz\.local, path: ^/api/steps    , role: ROLE_COCKTAILS }
        - { host: api\.automatiz\.local, path: ^/api/users    , role: ROLE_USER }

        - { host: automatiz\.local, path: ^/api/cocktails, role: IS_AUTHENTICATED_FULLY }
        - { host: automatiz\.local, path: ^/api/steps    , role: IS_AUTHENTICATED_FULLY }
        - { host: automatiz\.local, path: ^/api/me, role: IS_AUTHENTICATED_FULLY }
        - { host: automatiz\.local, path: ^/api/users    , role: ROLE_ADMIN }