cocktail_all:
    path:  /api/cocktails
    defaults: { _controller: AutomatizApiBundle:CocktailApi:all, _format: json}
    methods: [GET]

cocktail_get:
    path:  /api/cocktails/{id}
    defaults: { _controller: AutomatizApiBundle:CocktailApi:get, _format: json}
    methods: [GET]
    requirements:
        id: "[a-z0-9]{13}"

cocktail_post:
    path:  /api/cocktails
    defaults: { _controller: AutomatizApiBundle:CocktailApi:new, _format: json}
    methods: [POST]

cocktail_put:
    path:  /api/cocktails/{id}
    defaults: { _controller: AutomatizApiBundle:CocktailApi:edit, _format: json}
    methods: [PUT]
    requirements:
        id: "[a-z0-9]{13}"

cocktail_delete:
    path:  /api/cocktails/{id}
    defaults: { _controller: AutomatizApiBundle:CocktailApi:remove, _format: json}
    methods: [DELETE]
    requirements:
        id: "[a-z0-9]{13}"

cocktail_all_steps:
    path:  /api/cocktails/{cocktailId}/steps
    defaults: { _controller: AutomatizApiBundle:StepApi:all, _format: json}
    methods: [GET]
    requirements:
        cocktailId: "[a-z0-9]{13}"

cocktail_post_steps:
    path:  /api/cocktails/{cocktailId}/steps
    defaults: { _controller: AutomatizApiBundle:StepApi:post, _format: json}
    methods: [POST]
    requirements:
        cocktailId: "[a-z0-9]{13}"

user_all:
    path:  /api/users
    defaults: { _controller: AutomatizApiBundle:UserApi:all, _format: json}
    methods: [GET]