user_api:
    resource: "@AutomatizApiBundle/Resources/config/routing/users.yml"

me_api:
    resource: "@AutomatizApiBundle/Resources/config/routing/me.yml"

cocktail_api:
    resource: "@AutomatizApiBundle/Resources/config/routing/cocktails.yml"

step_api:
    resource: "@AutomatizApiBundle/Resources/config/routing/steps.yml"

cocktail_image_api:
    resource: "@AutomatizApiBundle/Resources/config/routing/cocktailimage.yml"

stat_api:
    resource: "@AutomatizApiBundle/Resources/config/routing/stat.yml"