Automatiz\ApiBundle\Entity\Step:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [steps]
        description:
            expose: true
            groups: [steps]
        quantity:
            expose: true
            accessor:
                getter: getQuantitySerialize
            groups: [steps]
        liquid:
            expose: true
            type: string
            accessor:
                getter: getLiquidSerialize
            groups: [steps]
        addIce:
            expose: true
            serialized_name: addIce
            accessor:
                getter: getAddIceSerialize
            groups: [steps]
