Automatiz\ApiBundle\Entity\Step:
    exclusion_policy: ALL
    properties:
        description:
            expose: true
            groups: [cocktail_detail]
        quantity:
            expose: true
            accessor:
                getter: getQuantitySerialize
            groups: [cocktail_detail]
        addIce:
            expose: true
            serialized_name: addIce
            accessor:
                getter: getAddIceSerialize
            groups: [cocktail_detail]
    virtual_properties:
        getLiquidSerialize:
            groups: [cocktail_detail]
            type: string
            serialized_name: liquid