Automatiz\ApiBundle\Entity\Cocktail:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [default, details]
        name:
            expose: true
            groups: [default, details]
        hasAlcoohol:
            expose: true
            serialized_name: hasAlcohol
            groups: [default, details]
        createdAt:
            expose: true
            groups: [default, details]
        updatedAt:
            expose: true
            groups: [default, details]
        note:
            expose: true
            groups: [default, details]
        description:
            expose: true
            groups: [default, details]
        steps:
            expose: true
            groups: [details]
        user:
            expose: true
            groups: [details]

    virtual_properties:
        getImageUrl:
            groups: [default, details]
            type: string
            serialized_name: image
    relations:
        -
            rel: self
            href:
                route: cocktail_get
                parameters:
                    id: expr(object.id)
                absolute: true