Automatiz\ApiBundle\Entity\Cocktail:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [cocktail_info, cocktail_detail]
        name:
            expose: true
            groups: [cocktail_info, cocktail_detail]
        hasAlcoohol:
            expose: true
            serialized_name: has_alcohol
            groups: [cocktail_info, cocktail_detail]
        createdAt:
            expose: true
            groups: [cocktail_info, cocktail_detail]
        updatedAt:
            expose: true
            groups: [cocktail_info, cocktail_detail]
        description:
            expose: true
            groups: [cocktail_info, cocktail_detail]
        user:
            expose: true
            groups: [cocktail_info, cocktail_detail]
        notes:
            expose: true
            max_depth: 10
            groups: [cocktail_detail]
        steps:
            expose: true
            groups: [cocktail_detail]


    virtual_properties:
        getImageUrl:
            groups: [cocktail_info, cocktail_detail]
            type: string
            serialized_name: image
        getNoteInfo:
            groups: [cocktail_info, cocktail_detail]
            type: double
            serialized_name: note_avairage