<?php

namespace Automatiz\ApiBundle\Entity;

/**
 * CocktailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CocktailRepository extends \Doctrine\ORM\EntityRepository
{
}
