automatiz_share:
    path: /share/{id}
    host: "automatiz.local"
    defaults: { _controller: AutomatizAppBundle:Share:share}
    methods: [GET]
    requirements:
        id: "[a-z0-9]{13}"

automatiz_app:
    path:     /
    defaults: { _controller: AutomatizAppBundle:Default:index }
    host: "automatiz.local"
    methods: [GET]


automatiz_app_route1:
    path: /{slug}
    defaults: { _controller: AutomatizAppBundle:Default:app }
    host: "automatiz.local"
    methods: [GET]

automatiz_app_route2:
    path: /{slug}/{slug2}
    defaults: { _controller: AutomatizAppBundle:Default:app }
    host: "automatiz.local"
    methods: [GET]

#automatiz_app_route_cocktail_get:
#    path: /cocktails/{id}
#    defaults: { _controller: AutomatizAppBundle:Default:app }
#    host: "automatiz.local"
#    methods: [GET]
#    requirements:
#        id: "[a-z0-9]{13}"
#
#automatiz_app_route_cocktail_slug:
#    path: /cocktails/{slug}
#    defaults: { _controller: AutomatizAppBundle:Default:app }
#    host: "automatiz.local"
#    methods: [GET]
#
#automatiz_app_route_user:
#    path: /users
#    defaults: { _controller: AutomatizAppBundle:Default:app }
#    host: "automatiz.local"
#    methods: [GET]
#    requirements:
#        id: "[a-z0-9]{13}"
#
#automatiz_app_route_user_get:
#    path: /users/{id}
#    defaults: { _controller: AutomatizAppBundle:Default:app }
#    host: "automatiz.local"
#    methods: [GET]
#    requirements:
#        id: "[a-z0-9]{13}"
#
#automatiz_app_route_cocktail:
#    path: /cocktails
#    defaults: { _controller: AutomatizAppBundle:Default:app }
#    host: "automatiz.local"
#    methods: [GET]

