automatiz_app:
    path:     /
    defaults: { _controller: AutomatizAppBundle:Default:index }

automatiz_app_slug:
    path:     /{slug}
    defaults: { _controller: AutomatizAppBundle:Default:index }